target: PreGenDataset
params:

  data_root: './outputs'

  org_h: 1024
  org_w: 1024
  H: 512
  W: 512
  word_len: [6, 12]
  seq_len: 12

  prompt_path: './configs/dataset/prompts.txt'
  creativebench: False

  # model cfg
  type: "test"
  load_ckpt_path: "./checkpoints/pretrained/sd_xl_base_1.0.safetensors"  #512-inpainting-ema.ckpt
  model_cfg_path: "./configs/test/sd_xl_base.yaml"  #sd_2_inpainting.yaml
  channel: 4 # AE latent channel
  factor: 8 # AE downsample factor
  scale: [5.0, 0.0]
  noise_iters: 0
  force_uc_zero_embeddings: []

  steps: 50
  init_step: 0
  batch_size: 1
  num_workers: 0
  gpu: 4
  dual_conditioner: False