target: TruetypeDataset
params:

  data_root: '/data/zhaoym/TextDesign-XL'
  length: 10000

  H: 512
  W: 512
  amp_factor: 1.2
  char_w: [56, 64]
  char_h_ratio: [1.2, 2.0]
  word_len: [4, 8]

  pre_render: True
  multi_color: True
