type: "train"

# path
load_ckpt_path: ./checkpoints/st-epoch=15-step=100000.ckpt # sd_xl_base_1.0.safetensors  512-inpainting-ema.ckpt
save_ckpt_dir: ./checkpoints
model_cfg_path: ./configs/train/textdesign_sd_2.yaml
dataset_cfg_path: ./configs/dataset/locr.yaml

# param
save_ckpt_freq: 1
num_workers: 0
batch_size: 2
base_learning_rate: 5.0e-5
shuffle: False

# runtime
lightning:
  max_epochs: 100
  accelerator: gpu
  strategy: ddp_find_unused_parameters_true
  accumulate_grad_batches: 4 
  devices: 
    - 1
    - 2
  default_root_dir: ./logs/base_logs
  profiler: simple 